### ISSUE TITLE
Array Index overflow issue.

### ISSUE THREAD

**Issue by grantlj** [rbgirshick/voc-dpm#10] opened 2015-09-18 11:40 UTC
parsing model
??? Subscript indices must either be real positive integers or logicals.

Error in ==> train at 217
model.thresh = pos_vals(ceil(length(pos_vals)*0.05));

**Comment by rbgirshick** [comment] 2015-09-18 15:43
Closing due to no useful information on how to reproduce this issue.

**Closed by rbgirshick** 2015-09-18 15:43 UTC
